DirectMarketing = read.csv("C:/Users/dc/Downloads/DirectMarketing.csv")
DirectMarketing = read.delim("C:/Users/dc/Downloads/DirectMarketing.csv", sep=";")
hist(DirectMarketing$AmountSpent)
d=density(DirectMarketing$AmountSpent)
plot(d)
install.packages("ggplot2")
library(ggplot2)
houseprice = read.csv("C:/Users/dc/Downloads/houseprice.csv")
houseprice = read.delim("C:/Users/dc/Downloads/houseprice.csv", sep=";")
qplot(houseprice$Price, houseprice$SqFt)
plot(houseprice$Price, houseprice$SqFt)
