# -*- coding: utf-8 -*-
"""prakstatis82

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KgwBoKvwtKMy8EGFPb6zuJqFSZ_Kdfxq
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

import pandas as pd
#from pandas.tools import plotting
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

data_Nadin = pd.read_csv('/content/houseprice.csv', sep = ';')
data_Nadin.head(5)

col_list = ['Price', 'Bedrooms']
numhouse = data_Nadin[data_Nadin.columns[data_Nadin.columns.isin(col_list)]]
numhouse.plot.scatter(x = 'Bedrooms', y = 'Price')

col_list = ['Price', 'Bathrooms']
numhouse = data_Nadin[data_Nadin.columns[data_Nadin.columns.isin(col_list)]]
numhouse.plot.scatter(x = 'Bathrooms', y = 'Price')

col_list = ['Price', 'Bathrooms']
numhouse = data_Nadin[data_Nadin.columns[data_Nadin.columns.isin(col_list)]]
plt.figure(figsize=(15,5))
numhouse.boxplot(by='Bathrooms')
plt.show()